export type ChallengeCategoryKey = "5_minut" | "wieczor" | "w_domu" | "wyjscie" | "smieszne" | "bliskosc" | "weekend" | "za_darmo";

export interface Challenge {
  id: string;
  text: string;
  rewardPaws: number;
  category: ChallengeCategoryKey;
}

export const CHALLENGE_CATEGORY_LABELS: Record<ChallengeCategoryKey, string> = {
  "5_minut": "5 minut",
  wieczor: "Wieczór",
  w_domu: "W domu",
  wyjscie: "Wyjście",
  smieszne: "Głupkowate",
  bliskosc: "Bliskość",
  weekend: "Weekend",
  za_darmo: "Bez wydawania",
};

export const CHALLENGES: Challenge[] = [
  { id: "5_minut-01", category: "5_minut", rewardPaws: 3, text: 'Przez pięć minut opowiedzcie sobie po jednej rzeczy z dzisiejszego dnia, której druga osoba jeszcze nie zna.' },
  { id: "5_minut-02", category: "5_minut", rewardPaws: 3, text: 'Zróbcie sobie herbatę albo wodę i usiądźcie obok siebie bez telefonów.' },
  { id: "5_minut-03", category: "5_minut", rewardPaws: 3, text: 'Każde wybiera jedną piosenkę, której chce dziś posłuchać razem.' },
  { id: "5_minut-04", category: "5_minut", rewardPaws: 3, text: 'Powiedz partnerowi jedną drobną rzecz, którą ostatnio doceniłeś/aś.' },
  { id: "5_minut-05", category: "5_minut", rewardPaws: 3, text: 'Znajdźcie w galerii jedno zdjęcie, które was dziś rozśmiesza.' },
  { id: "5_minut-06", category: "5_minut", rewardPaws: 3, text: 'Przez chwilę posiedźcie razem przy otwartym oknie albo na balkonie.' },
  { id: "5_minut-07", category: "5_minut", rewardPaws: 3, text: 'Każde mówi jedną rzecz, na którą czeka w tym tygodniu.' },
  { id: "5_minut-08", category: "5_minut", rewardPaws: 3, text: 'Zróbcie szybki ranking trzech przekąsek, które oboje lubicie.' },
  { id: "5_minut-09", category: "5_minut", rewardPaws: 3, text: 'Wymyślcie jedno małe coś, co możecie zrobić razem jutro.' },
  { id: "5_minut-10", category: "5_minut", rewardPaws: 3, text: 'Przytulcie się przez chwilę bez rozmawiania.' },
  { id: "5_minut-11", category: "5_minut", rewardPaws: 3, text: 'Każde wybiera jedno słowo opisujące dzisiejszy dzień i mówi dlaczego.' },
  { id: "5_minut-12", category: "5_minut", rewardPaws: 3, text: 'Zróbcie sobie nawzajem najgorsze możliwe zdjęcie.' },
  { id: "5_minut-13", category: "5_minut", rewardPaws: 3, text: 'Przez pięć minut opowiadajcie sobie o kompletnie nieistotnych rzeczach.' },
  { id: "5_minut-14", category: "5_minut", rewardPaws: 3, text: 'Wybierzcie wspólnie jedną rzecz do obejrzenia później.' },
  { id: "5_minut-15", category: "5_minut", rewardPaws: 3, text: 'Każde pokazuje drugiemu ostatnią rzecz, którą zapisało sobie „na później”.' },
  { id: "wieczor-01", category: "wieczor", rewardPaws: 4, text: 'Obejrzyjcie razem jeden odcinek czegoś, co oboje lubicie.' },
  { id: "wieczor-02", category: "wieczor", rewardPaws: 4, text: 'Zróbcie wspólną kolację z tego, co już macie w domu.' },
  { id: "wieczor-03", category: "wieczor", rewardPaws: 4, text: 'Odłóżcie telefony na 20 minut i pobądźcie razem.' },
  { id: "wieczor-04", category: "wieczor", rewardPaws: 4, text: 'Wybierzcie film, którego żadne z was wcześniej nie widziało.' },
  { id: "wieczor-05", category: "wieczor", rewardPaws: 4, text: 'Zróbcie małą degustację rzeczy znalezionych w kuchni.' },
  { id: "wieczor-06", category: "wieczor", rewardPaws: 4, text: 'Zgaście główne światło i zróbcie spokojniejszy wieczór przy lampce.' },
  { id: "wieczor-07", category: "wieczor", rewardPaws: 4, text: 'Każde wybiera po jednym krótkim filmiku, który chce pokazać drugiej osobie.' },
  { id: "wieczor-08", category: "wieczor", rewardPaws: 4, text: 'Przejrzyjcie wspólne zdjęcia z jednego wybranego miesiąca.' },
  { id: "wieczor-09", category: "wieczor", rewardPaws: 4, text: 'Zaplanujcie jedno małe wyjście na najbliższe dni.' },
  { id: "wieczor-10", category: "wieczor", rewardPaws: 4, text: 'Posłuchajcie razem jednej pełnej płyty albo playlisty.' },
  { id: "wieczor-11", category: "wieczor", rewardPaws: 4, text: 'Zróbcie coś do picia i porozmawiajcie przy stole zamiast na kanapie.' },
  { id: "wieczor-12", category: "wieczor", rewardPaws: 4, text: 'Każde opowiada o jednej rzeczy, która dziś zajęła mu najwięcej myśli.' },
  { id: "wieczor-13", category: "wieczor", rewardPaws: 4, text: 'Zróbcie prostą przekąskę i oceńcie ją jak jurorzy programu kulinarnego.' },
  { id: "wieczor-14", category: "wieczor", rewardPaws: 4, text: 'Znajdźcie po jednym miejscu, do którego chcielibyście kiedyś pojechać.' },
  { id: "wieczor-15", category: "wieczor", rewardPaws: 4, text: 'Zróbcie wieczór bez przewijania social mediów przez pół godziny.' },
  { id: "w_domu-01", category: "w_domu", rewardPaws: 4, text: 'Zróbcie razem coś prostego do jedzenia, czego dawno nie robiliście.' },
  { id: "w_domu-02", category: "w_domu", rewardPaws: 4, text: 'Przestawcie albo udekorujcie jeden mały fragment pokoju.' },
  { id: "w_domu-03", category: "w_domu", rewardPaws: 4, text: 'Zbudujcie razem playlistę z dziesięciu piosenek.' },
  { id: "w_domu-04", category: "w_domu", rewardPaws: 4, text: 'Zagrajcie w dowolną krótką grę bez telefonu.' },
  { id: "w_domu-05", category: "w_domu", rewardPaws: 4, text: 'Wybierzcie jedno stare zdjęcie i spróbujcie odtworzyć je dzisiaj.' },
  { id: "w_domu-06", category: "w_domu", rewardPaws: 4, text: 'Zróbcie mini konkurs na najładniej podaną przekąskę.' },
  { id: "w_domu-07", category: "w_domu", rewardPaws: 4, text: 'Każde wybiera jedną rzecz, którą drugie ma narysować w 60 sekund.' },
  { id: "w_domu-08", category: "w_domu", rewardPaws: 4, text: 'Zróbcie wspólnie listę pięciu rzeczy, które chcecie zrobić jesienią, zimą albo latem.' },
  { id: "w_domu-09", category: "w_domu", rewardPaws: 4, text: 'Zaparzcie coś dobrego i zróbcie dziesięć minut spokojnej rozmowy.' },
  { id: "w_domu-10", category: "w_domu", rewardPaws: 4, text: 'Znajdźcie najdziwniejszy przedmiot w domu i wymyślcie mu nową funkcję.' },
  { id: "w_domu-11", category: "w_domu", rewardPaws: 4, text: 'Zróbcie razem porządek w jednym małym miejscu przy ulubionej muzyce.' },
  { id: "w_domu-12", category: "w_domu", rewardPaws: 4, text: 'Każde wybiera jedną rzecz w domu, która kojarzy mu się z drugim.' },
  { id: "w_domu-13", category: "w_domu", rewardPaws: 4, text: 'Wymyślcie własny przepis z maksymalnie pięciu składników.' },
  { id: "w_domu-14", category: "w_domu", rewardPaws: 4, text: 'Zróbcie domowy wieczór tematyczny inspirowany jednym krajem.' },
  { id: "w_domu-15", category: "w_domu", rewardPaws: 4, text: 'Przygotujcie sobie nawzajem prostą niespodziankę z rzeczy, które już macie.' },
  { id: "wyjscie-01", category: "wyjscie", rewardPaws: 5, text: 'Idźcie na spacer bez konkretnej trasy przez minimum 20 minut.' },
  { id: "wyjscie-02", category: "wyjscie", rewardPaws: 5, text: 'Znajdźcie miejsce w okolicy, w którym jeszcze razem nie byliście.' },
  { id: "wyjscie-03", category: "wyjscie", rewardPaws: 5, text: 'Idźcie po jedną małą rzecz do jedzenia i zjedzcie ją na zewnątrz.' },
  { id: "wyjscie-04", category: "wyjscie", rewardPaws: 5, text: 'Zróbcie spacer fotograficzny: każde robi trzy zdjęcia rzeczy, które mu się podobają.' },
  { id: "wyjscie-05", category: "wyjscie", rewardPaws: 5, text: 'Usiądźcie gdzieś na ławce i przez chwilę poobserwujcie ludzi.' },
  { id: "wyjscie-06", category: "wyjscie", rewardPaws: 5, text: 'Wybierzcie ulicę albo drogę, którą zwykle omijacie, i przejdźcie się nią.' },
  { id: "wyjscie-07", category: "wyjscie", rewardPaws: 5, text: 'Idźcie zobaczyć zachód słońca, jeśli pogoda pozwala.' },
  { id: "wyjscie-08", category: "wyjscie", rewardPaws: 5, text: 'Zróbcie małe wyjście bez sprawdzania telefonu przez pierwsze 15 minut.' },
  { id: "wyjscie-09", category: "wyjscie", rewardPaws: 5, text: 'Znajdźcie kawiarnię, piekarnię albo miejsce, którego wcześniej nie próbowaliście.' },
  { id: "wyjscie-10", category: "wyjscie", rewardPaws: 5, text: 'Idźcie do księgarni i każde wybiera książkę, którą poleciłoby drugiemu.' },
  { id: "wyjscie-11", category: "wyjscie", rewardPaws: 5, text: 'Zróbcie wspólne zdjęcie w miejscu, przez które często tylko przechodzicie.' },
  { id: "wyjscie-12", category: "wyjscie", rewardPaws: 5, text: 'Przejdźcie się tam, gdzie jedno z was lubiło chodzić wcześniej samo.' },
  { id: "wyjscie-13", category: "wyjscie", rewardPaws: 5, text: 'Idźcie na krótki spacer po zmroku w dobrze oświetlonej okolicy.' },
  { id: "wyjscie-14", category: "wyjscie", rewardPaws: 5, text: 'Zróbcie mini wycieczkę komunikacją do losowego znanego wam miejsca.' },
  { id: "wyjscie-15", category: "wyjscie", rewardPaws: 5, text: 'Znajdźcie po drodze coś, co mogłoby być nowym „naszym miejscem”.' },
  { id: "smieszne-01", category: "smieszne", rewardPaws: 4, text: 'Przez pięć minut mówcie do siebie jak prezenterzy wiadomości.' },
  { id: "smieszne-02", category: "smieszne", rewardPaws: 4, text: 'Każde wybiera dla drugiej osoby najgorszą możliwą nazwę superbohatera.' },
  { id: "smieszne-03", category: "smieszne", rewardPaws: 4, text: 'Wymyślcie trzy absurdalne zasady, które obowiązywałyby w waszym wspólnym państwie.' },
  { id: "smieszne-04", category: "smieszne", rewardPaws: 4, text: 'Zróbcie sobie zdjęcie udające okładkę bardzo poważnego magazynu.' },
  { id: "smieszne-05", category: "smieszne", rewardPaws: 4, text: 'Każde ma minutę na narysowanie kota drugiej osoby bez odrywania ręki.' },
  { id: "smieszne-06", category: "smieszne", rewardPaws: 4, text: 'Wymyślcie najgorszy możliwy slogan reklamowy dla Meow.' },
  { id: "smieszne-07", category: "smieszne", rewardPaws: 4, text: 'Przez chwilę odpowiadajcie sobie tylko tytułami filmów albo piosenek.' },
  { id: "smieszne-08", category: "smieszne", rewardPaws: 4, text: 'Wymyślcie menu restauracji, w której każde danie brzmi podejrzanie.' },
  { id: "smieszne-09", category: "smieszne", rewardPaws: 4, text: 'Zróbcie konkurs na najbardziej dramatyczne przeczytanie zwykłej wiadomości.' },
  { id: "smieszne-10", category: "smieszne", rewardPaws: 4, text: 'Wymyślcie sobie nawzajem kompletnie niepraktyczne zawody.' },
  { id: "smieszne-11", category: "smieszne", rewardPaws: 4, text: 'Każde wybiera trzy rzeczy, które zabrałoby na absurdalną bezludną wyspę.' },
  { id: "smieszne-12", category: "smieszne", rewardPaws: 4, text: 'Przez dwie minuty udawajcie, że właśnie poznaliście się pierwszy raz.' },
  { id: "smieszne-13", category: "smieszne", rewardPaws: 4, text: 'Nagrajcie krótkie, celowo nieudane intro do fikcyjnego vloga.' },
  { id: "smieszne-14", category: "smieszne", rewardPaws: 4, text: 'Wymyślcie imiona dla pięciu hipotetycznych kotów.' },
  { id: "smieszne-15", category: "smieszne", rewardPaws: 4, text: 'Zróbcie ranking najbardziej absurdalnych zakupów, jakie moglibyście zrobić po wygranej na loterii.' },
  { id: "bliskosc-01", category: "bliskosc", rewardPaws: 5, text: 'Powiedz partnerowi jedną rzecz, przy której czujesz się przez niego/nią wspierany/a.' },
  { id: "bliskosc-02", category: "bliskosc", rewardPaws: 5, text: 'Zapytaj partnera, czego dziś najbardziej potrzebuje, i tylko wysłuchaj odpowiedzi.' },
  { id: "bliskosc-03", category: "bliskosc", rewardPaws: 5, text: 'Powiedzcie sobie po jednej rzeczy, którą cenicie w waszej codzienności.' },
  { id: "bliskosc-04", category: "bliskosc", rewardPaws: 5, text: 'Przypomnijcie sobie moment, kiedy ostatnio naprawdę dobrze się razem bawiliście.' },
  { id: "bliskosc-05", category: "bliskosc", rewardPaws: 5, text: 'Każde mówi jedną rzecz, którą chce częściej robić razem.' },
  { id: "bliskosc-06", category: "bliskosc", rewardPaws: 5, text: 'Powiedzcie sobie, co ostatnio sprawiło, że czuliście się blisko.' },
  { id: "bliskosc-07", category: "bliskosc", rewardPaws: 5, text: 'Przez chwilę przytulcie się albo usiądźcie blisko bez konieczności rozmowy.' },
  { id: "bliskosc-08", category: "bliskosc", rewardPaws: 5, text: 'Każde mówi jedną rzecz, za którą jest dziś wdzięczne drugiej osobie.' },
  { id: "bliskosc-09", category: "bliskosc", rewardPaws: 5, text: 'Porozmawiajcie przez dziesięć minut bez prób naprawiania czegokolwiek.' },
  { id: "bliskosc-10", category: "bliskosc", rewardPaws: 5, text: 'Zapytajcie się nawzajem: „Co mogę zrobić, żeby Twój wieczór był trochę lepszy?”' },
  { id: "bliskosc-11", category: "bliskosc", rewardPaws: 5, text: 'Każde przypomina jedno wspólne wspomnienie, które lubi wracać w głowie.' },
  { id: "bliskosc-12", category: "bliskosc", rewardPaws: 5, text: 'Powiedzcie sobie jedną rzecz, której ostatnio o sobie nie mówiliście.' },
  { id: "bliskosc-13", category: "bliskosc", rewardPaws: 5, text: 'Każde kończy zdanie: „Lubię, kiedy my…”' },
  { id: "bliskosc-14", category: "bliskosc", rewardPaws: 5, text: 'Zastanówcie się nad jednym małym rytuałem, który chcielibyście mieć częściej.' },
  { id: "bliskosc-15", category: "bliskosc", rewardPaws: 5, text: 'Powiedz partnerowi, w jakiej sytuacji ostatnio poczułeś/aś, że naprawdę jest po Twojej stronie.' },
  { id: "weekend-01", category: "weekend", rewardPaws: 6, text: 'Zaplanujcie pół dnia bez dokładnego harmonogramu i zobaczcie, co z tego wyjdzie.' },
  { id: "weekend-02", category: "weekend", rewardPaws: 6, text: 'Znajdźcie miejsce do krótkiego wypadu w promieniu około godziny drogi.' },
  { id: "weekend-03", category: "weekend", rewardPaws: 6, text: 'Zróbcie wspólne śniadanie bez pośpiechu.' },
  { id: "weekend-04", category: "weekend", rewardPaws: 6, text: 'Wybierzcie jedną rzecz, której żadne z was jeszcze nie próbowało.' },
  { id: "weekend-05", category: "weekend", rewardPaws: 6, text: 'Zorganizujcie mini randkę za możliwie mały budżet.' },
  { id: "weekend-06", category: "weekend", rewardPaws: 6, text: 'Zróbcie sobie pół godziny spaceru i potem wybierzcie coś dobrego do jedzenia.' },
  { id: "weekend-07", category: "weekend", rewardPaws: 6, text: 'Każde proponuje jeden plan na weekend, a potem łączycie oba.' },
  { id: "weekend-08", category: "weekend", rewardPaws: 6, text: 'Zróbcie dzień ze wspólną playlistą zamiast przypadkowej muzyki.' },
  { id: "weekend-09", category: "weekend", rewardPaws: 6, text: 'Znajdźcie lokalne wydarzenie, wystawę albo miejsce, które brzmi choć trochę ciekawie.' },
  { id: "weekend-10", category: "weekend", rewardPaws: 6, text: 'Zróbcie mały piknik, nawet jeśli ma być tylko na ławce.' },
  { id: "weekend-11", category: "weekend", rewardPaws: 6, text: 'Przygotujcie wspólnie coś, czego normalnie nie jecie na śniadanie.' },
  { id: "weekend-12", category: "weekend", rewardPaws: 6, text: 'Zróbcie wyjście, podczas którego każde wybiera jeden przystanek.' },
  { id: "weekend-13", category: "weekend", rewardPaws: 6, text: 'Zaplanujcie jeden całkowicie wolny wieczór bez dodatkowych zobowiązań.' },
  { id: "weekend-14", category: "weekend", rewardPaws: 6, text: 'Zróbcie zdjęcie, które trafi do wspomnień Meow.' },
  { id: "weekend-15", category: "weekend", rewardPaws: 6, text: 'Wrzućcie trzy nowe pomysły do Słoika i jeden z nich wylosujcie.' },
  { id: "za_darmo-01", category: "za_darmo", rewardPaws: 4, text: 'Idźcie na spacer w miejsce, którego dawno nie odwiedzaliście.' },
  { id: "za_darmo-02", category: "za_darmo", rewardPaws: 4, text: 'Zróbcie w domu wieczór z filmem, który już macie dostępny.' },
  { id: "za_darmo-03", category: "za_darmo", rewardPaws: 4, text: 'Przygotujcie razem coś z produktów, które zostały w kuchni.' },
  { id: "za_darmo-04", category: "za_darmo", rewardPaws: 4, text: 'Przejrzyjcie stare zdjęcia i wybierzcie pięć ulubionych.' },
  { id: "za_darmo-05", category: "za_darmo", rewardPaws: 4, text: 'Zróbcie sobie nawzajem playlistę z pięciu utworów.' },
  { id: "za_darmo-06", category: "za_darmo", rewardPaws: 4, text: 'Zaplanujcie przyszłą wycieczkę tylko dla zabawy, bez kupowania czegokolwiek.' },
  { id: "za_darmo-07", category: "za_darmo", rewardPaws: 4, text: 'Usiądźcie razem na zewnątrz i porozmawiajcie przez 20 minut.' },
  { id: "za_darmo-08", category: "za_darmo", rewardPaws: 4, text: 'Zróbcie quiz z rzeczy, które pamiętacie o sobie.' },
  { id: "za_darmo-09", category: "za_darmo", rewardPaws: 4, text: 'Każde opowiada jedną historię z dzieciństwa, której drugie nie zna.' },
  { id: "za_darmo-10", category: "za_darmo", rewardPaws: 4, text: 'Zróbcie serię śmiesznych zdjęć telefonem.' },
  { id: "za_darmo-11", category: "za_darmo", rewardPaws: 4, text: 'Znajdźcie w domu rzeczy, z których można zrobić małą dekorację albo pamiątkę.' },
  { id: "za_darmo-12", category: "za_darmo", rewardPaws: 4, text: 'Zagrajcie w „co wybierzesz?” wymyślając pytania na zmianę.' },
  { id: "za_darmo-13", category: "za_darmo", rewardPaws: 4, text: 'Zróbcie listę dziesięciu darmowych rzeczy, które lubicie robić razem.' },
  { id: "za_darmo-14", category: "za_darmo", rewardPaws: 4, text: 'Posłuchajcie razem całego albumu bez robienia niczego innego.' },
  { id: "za_darmo-15", category: "za_darmo", rewardPaws: 4, text: 'Zapiszcie jedno wspomnienie z dzisiejszego dnia w Meow.' },
 ];

export function getChallengeById(id: string): Challenge | undefined {
  return CHALLENGES.find((challenge) => challenge.id === id);
}

export function pickDailyChallenge(seed: string): Challenge {
  let hash = 2166136261;
  for (let i = 0; i < seed.length; i += 1) {
    hash ^= seed.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return CHALLENGES[Math.abs(hash >>> 0) % CHALLENGES.length];
}
