export type QuestionDepth = "light" | "medium" | "deep";
export type QuestionCategoryKey = "bliskosc" | "poznaj_mnie" | "na_luzie" | "relacja" | "przyszlosc" | "dziecinstwo" | "codziennosc" | "marzenia" | "hipotetyczne" | "szczerze";
export interface QuestionCategory {
  key: QuestionCategoryKey;
  label: string;
  description: string;
  defaultDepth: QuestionDepth;
}

export interface Question {
  id: string;
  category: QuestionCategoryKey;
  text: string;
  depth: QuestionDepth;
  tags?: string[];
}

export const QUESTION_CATEGORIES: QuestionCategory[] = [
  { key: "bliskosc", label: 'Bliskość', description: 'O drobnych rzeczach, które dają poczucie bycia blisko', defaultDepth: "medium" },
  { key: "poznaj_mnie", label: 'Poznaj mnie', description: 'Preferencje, reakcje i małe rzeczy, które budują obraz drugiej osoby', defaultDepth: "light" },
  { key: "na_luzie", label: 'Na luzie', description: 'Pytania bez ciężaru — bardziej do uśmiechu niż analizowania', defaultDepth: "light" },
  { key: "relacja", label: 'Nas', description: 'O tym, jak działa Wasza codzienność i co warto w niej pielęgnować', defaultDepth: "medium" },
  { key: "przyszlosc", label: 'Przyszłość', description: 'Plany, marzenia i rzeczy, które dobrze jest kiedyś zrobić razem', defaultDepth: "medium" },
  { key: "dziecinstwo", label: 'Dzieciństwo', description: 'Historie sprzed Waszego poznania, które pomagają lepiej rozumieć siebie', defaultDepth: "medium" },
  { key: "codziennosc", label: 'Codzienność', description: 'Małe preferencje, które często mają większe znaczenie niż wielkie deklaracje', defaultDepth: "light" },
  { key: "marzenia", label: 'Marzenia', description: 'O rzeczach trochę większych, trochę dziwnych i czasem jeszcze bez planu', defaultDepth: "medium" },
  { key: "hipotetyczne", label: 'Co gdyby…', description: 'Scenariusze, które nie mają poprawnej odpowiedzi', defaultDepth: "light" },
  { key: "szczerze", label: 'Szczerze', description: 'Głębsze pytania na moment, kiedy oboje macie na nie przestrzeń', defaultDepth: "deep" },
];

export const QUESTIONS: Question[] = [
  { id: "bliskosc-01", category: "bliskosc", depth: "medium", text: 'Kiedy ostatnio czułeś/czułaś się przeze mnie naprawdę zauważony/a?' },
  { id: "bliskosc-02", category: "bliskosc", depth: "medium", text: 'Jaki drobny gest ode mnie daje Ci najwięcej ciepła?' },
  { id: "bliskosc-03", category: "bliskosc", depth: "medium", text: 'W jakiej sytuacji najłatwiej czujesz, że jesteśmy po tej samej stronie?' },
  { id: "bliskosc-04", category: "bliskosc", depth: "medium", text: 'Co najbardziej lubisz w naszych spokojnych chwilach razem?' },
  { id: "bliskosc-05", category: "bliskosc", depth: "medium", text: 'Po czym poznajesz, że naprawdę Cię słucham?' },
  { id: "bliskosc-06", category: "bliskosc", depth: "medium", text: 'Jaki rodzaj czułości jest dla Ciebie najbardziej naturalny?' },
  { id: "bliskosc-07", category: "bliskosc", depth: "medium", text: 'Co sprawia, że przy mnie łatwiej Ci być sobą?' },
  { id: "bliskosc-08", category: "bliskosc", depth: "medium", text: 'Który wspólny rytuał jest dla Ciebie ważniejszy, niż mogłoby się wydawać?' },
  { id: "bliskosc-09", category: "bliskosc", depth: "medium", text: 'Jaki zwykły moment z nami ostatnio szczególnie Ci się spodobał?' },
  { id: "bliskosc-10", category: "bliskosc", depth: "medium", text: 'Co mogę zrobić w gorszy dzień, żebyś poczuł/a, że jestem obok?' },
  { id: "bliskosc-11", category: "bliskosc", depth: "medium", text: 'Co najbardziej cenisz w sposobie, w jaki spędzamy czas tylko we dwoje?' },
  { id: "bliskosc-12", category: "bliskosc", depth: "medium", text: 'Jaka forma wsparcia ode mnie działa na Ciebie najlepiej?' },
  { id: "bliskosc-13", category: "bliskosc", depth: "medium", text: 'Co pomaga Ci poczuć spokój, kiedy jesteśmy razem?' },
  { id: "bliskosc-14", category: "bliskosc", depth: "medium", text: 'Jaka wspólna chwila daje Ci poczucie bezpieczeństwa?' },
  { id: "bliskosc-15", category: "bliskosc", depth: "medium", text: 'Co chciałbyś/chciałabyś częściej robić bez żadnego planu?' },
  { id: "bliskosc-16", category: "bliskosc", depth: "medium", text: 'W jakich momentach czujesz największą bliskość między nami?' },
  { id: "bliskosc-17", category: "bliskosc", depth: "medium", text: 'Jaki mój gest potrafi szybko poprawić Ci nastrój?' },
  { id: "bliskosc-18", category: "bliskosc", depth: "medium", text: 'Co najbardziej lubisz w naszych przytuleniach albo bliskości fizycznej?' },
  { id: "bliskosc-19", category: "bliskosc", depth: "medium", text: 'Co sprawia, że rozmowa ze mną jest dla Ciebie łatwiejsza?' },
  { id: "bliskosc-20", category: "bliskosc", depth: "medium", text: 'Jaki mały zwyczaj chciałbyś/chciałabyś, żeby został z nami na długo?' },
  { id: "bliskosc-21", category: "bliskosc", depth: "medium", text: 'Co mogę robić częściej, żebyś czuł/a się ważny/a?' },
  { id: "bliskosc-22", category: "bliskosc", depth: "medium", text: 'Jaki moment dnia najbardziej lubisz dzielić ze mną?' },
  { id: "bliskosc-23", category: "bliskosc", depth: "medium", text: 'Co w naszej codzienności daje Ci poczucie „domu”?' },
  { id: "bliskosc-24", category: "bliskosc", depth: "medium", text: 'Za jaki drobny gest ode mnie ostatnio byłeś/byłaś wdzięczny/a?' },
  { id: "bliskosc-25", category: "bliskosc", depth: "medium", text: 'Co chciałbyś/chciałabyś, żebyśmy robili częściej tylko dla przyjemności?' },
  { id: "poznaj-mnie-01", category: "poznaj_mnie", depth: "light", text: 'Co ostatnio najłatwiej poprawia Ci humor?' },
  { id: "poznaj-mnie-02", category: "poznaj_mnie", depth: "light", text: 'Jak najlepiej odpoczywasz po intensywnym dniu?' },
  { id: "poznaj-mnie-03", category: "poznaj_mnie", depth: "light", text: 'Co zazwyczaj robisz, kiedy potrzebujesz pobyć chwilę sam/a?' },
  { id: "poznaj-mnie-04", category: "poznaj_mnie", depth: "light", text: 'Jaka mała rzecz potrafi zepsuć Ci humor bardziej, niż powinna?' },
  { id: "poznaj-mnie-05", category: "poznaj_mnie", depth: "light", text: 'Co daje Ci najwięcej energii w zwykły dzień?' },
  { id: "poznaj-mnie-06", category: "poznaj_mnie", depth: "light", text: 'Jak wyglądałby Twój idealny wolny poranek?' },
  { id: "poznaj-mnie-07", category: "poznaj_mnie", depth: "light", text: 'Jaki komplement pamiętasz najdłużej?' },
  { id: "poznaj-mnie-08", category: "poznaj_mnie", depth: "light", text: 'Co sprawia, że szybko czujesz się swobodnie w nowym miejscu?' },
  { id: "poznaj-mnie-09", category: "poznaj_mnie", depth: "light", text: 'Czego ludzie często o Tobie nie wiedzą, choć jest dla Ciebie ważne?' },
  { id: "poznaj-mnie-10", category: "poznaj_mnie", depth: "light", text: 'Jakie trzy rzeczy najczęściej poprawiają Ci dzień?' },
  { id: "poznaj-mnie-11", category: "poznaj_mnie", depth: "light", text: 'Co najłatwiej wyprowadza Cię z koncentracji?' },
  { id: "poznaj-mnie-12", category: "poznaj_mnie", depth: "light", text: 'Jaka część dnia jest zwykle najbardziej „Twoja”?' },
  { id: "poznaj-mnie-13", category: "poznaj_mnie", depth: "light", text: 'Jak reagujesz, gdy plan nagle się zmienia?' },
  { id: "poznaj-mnie-14", category: "poznaj_mnie", depth: "light", text: 'Co pomaga Ci wrócić do dobrego nastroju po nieudanym dniu?' },
  { id: "poznaj-mnie-15", category: "poznaj_mnie", depth: "light", text: 'Jaki typ niespodzianki naprawdę by Cię ucieszył?' },
  { id: "poznaj-mnie-16", category: "poznaj_mnie", depth: "light", text: 'Co wybierasz częściej: spontaniczność czy plan?' },
  { id: "poznaj-mnie-17", category: "poznaj_mnie", depth: "light", text: 'Jakie miejsce sprawia, że od razu czujesz się spokojniej?' },
  { id: "poznaj-mnie-18", category: "poznaj_mnie", depth: "light", text: 'Co najczęściej odkładasz na później?' },
  { id: "poznaj-mnie-19", category: "poznaj_mnie", depth: "light", text: 'Jaka rzecz zawsze Cię rozśmiesza?' },
  { id: "poznaj-mnie-20", category: "poznaj_mnie", depth: "light", text: 'Jak lubisz, żeby ktoś okazywał Ci zainteresowanie?' },
  { id: "poznaj-mnie-21", category: "poznaj_mnie", depth: "light", text: 'Co jest dla Ciebie ważniejsze podczas odpoczynku: cisza czy zajęcie czymś głowy?' },
  { id: "poznaj-mnie-22", category: "poznaj_mnie", depth: "light", text: 'Jak zachowujesz się, kiedy jesteś naprawdę podekscytowany/a?' },
  { id: "poznaj-mnie-23", category: "poznaj_mnie", depth: "light", text: 'Co ostatnio odkryłeś/aś o sobie?' },
  { id: "poznaj-mnie-24", category: "poznaj_mnie", depth: "light", text: 'Jaki zwyczaj chciałbyś/chciałabyś kiedyś zmienić?' },
  { id: "poznaj-mnie-25", category: "poznaj_mnie", depth: "light", text: 'Co najbardziej pomaga Ci poczuć, że dzień był dobrze spędzony?' },
  { id: "na-luzie-01", category: "na_luzie", depth: "light", text: 'Gdybyśmy mieli otworzyć małą knajpę, co byłoby jej specjalnością?' },
  { id: "na-luzie-02", category: "na_luzie", depth: "light", text: 'Które z nas lepiej poradziłoby sobie na bezludnej wyspie?' },
  { id: "na-luzie-03", category: "na_luzie", depth: "light", text: 'Gdyby nasze koty mogły mówić, o co najczęściej by się na nas skarżyły?' },
  { id: "na-luzie-04", category: "na_luzie", depth: "light", text: 'Jaką nazwę miałby serial oparty na naszym związku?' },
  { id: "na-luzie-05", category: "na_luzie", depth: "light", text: 'Które z nas szybciej wydałoby fortunę po wygranej na loterii?' },
  { id: "na-luzie-06", category: "na_luzie", depth: "light", text: 'Gdybyśmy przez tydzień mogli jeść tylko jedną kuchnię świata, którą wybierasz?' },
  { id: "na-luzie-07", category: "na_luzie", depth: "light", text: 'Jaki najdziwniejszy wspólny biznes moglibyśmy prowadzić?' },
  { id: "na-luzie-08", category: "na_luzie", depth: "light", text: 'Gdybyśmy zamienili się obowiązkami na tydzień, co byłoby dla Ciebie najzabawniejsze?' },
  { id: "na-luzie-09", category: "na_luzie", depth: "light", text: 'Które z nas byłoby gorszym uczestnikiem reality show?' },
  { id: "na-luzie-10", category: "na_luzie", depth: "light", text: 'Gdybyśmy mogli teleportować się teraz gdziekolwiek na dwie godziny, dokąd?' },
  { id: "na-luzie-11", category: "na_luzie", depth: "light", text: 'Jakie zwierzę poza kotem najbardziej pasowałoby do naszego duetu?' },
  { id: "na-luzie-12", category: "na_luzie", depth: "light", text: 'Jaka piosenka byłaby absurdalnie dobrym hymnem naszego związku?' },
  { id: "na-luzie-13", category: "na_luzie", depth: "light", text: 'Gdybyśmy mieli wspólną supermoc, co powinna robić?' },
  { id: "na-luzie-14", category: "na_luzie", depth: "light", text: 'Które z nas szybciej zaprzyjaźniłoby się z przypadkową osobą na wakacjach?' },
  { id: "na-luzie-15", category: "na_luzie", depth: "light", text: 'Jaki tytuł miałaby książka o naszych najdziwniejszych sytuacjach?' },
  { id: "na-luzie-16", category: "na_luzie", depth: "light", text: 'Gdybyśmy musieli wystąpić w teleturnieju, jaki temat dałby nam największą szansę?' },
  { id: "na-luzie-17", category: "na_luzie", depth: "light", text: 'Co byłoby naszym najbardziej niepraktycznym wspólnym zakupem?' },
  { id: "na-luzie-18", category: "na_luzie", depth: "light", text: 'Gdybyśmy mieli przez miesiąc mieszkać w jednym fikcyjnym świecie, który wybierasz?' },
  { id: "na-luzie-19", category: "na_luzie", depth: "light", text: 'Które z nas częściej mówi „tylko na chwilę” i znika na godzinę?' },
  { id: "na-luzie-20", category: "na_luzie", depth: "light", text: 'Jaka rzecz z naszego domu najlepiej opisałaby nas jako parę?' },
  { id: "na-luzie-21", category: "na_luzie", depth: "light", text: 'Gdyby nasze koty miały tajny klub, co robiłyby podczas spotkań?' },
  { id: "na-luzie-22", category: "na_luzie", depth: "light", text: 'Jak wyglądałaby najgorsza randka, którą moglibyśmy celowo zaplanować?' },
  { id: "na-luzie-23", category: "na_luzie", depth: "light", text: 'Które z nas lepiej udawałoby detektywa?' },
  { id: "na-luzie-24", category: "na_luzie", depth: "light", text: 'Gdybyśmy mogli dostać darmowy zapas jednej rzeczy na całe życie, czego?' },
  { id: "na-luzie-25", category: "na_luzie", depth: "light", text: 'Jaki kompletnie niepotrzebny talent chcielibyśmy mieć razem?' },
  { id: "relacja-01", category: "relacja", depth: "medium", text: 'Co ostatnio zrobiliśmy dobrze jako para?' },
  { id: "relacja-02", category: "relacja", depth: "medium", text: 'Co sprawia, że czujesz, że gramy do jednej bramki?' },
  { id: "relacja-03", category: "relacja", depth: "medium", text: 'Która część naszej codzienności najbardziej Ci odpowiada?' },
  { id: "relacja-04", category: "relacja", depth: "medium", text: 'Co moglibyśmy uprościć w naszym wspólnym funkcjonowaniu?' },
  { id: "relacja-05", category: "relacja", depth: "medium", text: 'Kiedy najłatwiej nam się dogadać?' },
  { id: "relacja-06", category: "relacja", depth: "medium", text: 'Co chciałbyś/chciałabyś, żebyśmy robili częściej razem?' },
  { id: "relacja-07", category: "relacja", depth: "medium", text: 'Jaka rzecz w naszym związku z czasem stała się lepsza?' },
  { id: "relacja-08", category: "relacja", depth: "medium", text: 'Co najbardziej cenisz w tym, jak rozwiązujemy zwykłe problemy?' },
  { id: "relacja-09", category: "relacja", depth: "medium", text: 'Jaki wspólny zwyczaj warto według Ciebie chronić?' },
  { id: "relacja-10", category: "relacja", depth: "medium", text: 'Co sprawia, że czujesz się przeze mnie traktowany/a partnersko?' },
  { id: "relacja-11", category: "relacja", depth: "medium", text: 'Co ostatnio było dobrym przykładem naszego współdziałania?' },
  { id: "relacja-12", category: "relacja", depth: "medium", text: 'Jak możemy lepiej dawać sobie znać, że potrzebujemy przestrzeni?' },
  { id: "relacja-13", category: "relacja", depth: "medium", text: 'Jaka rzecz w naszym sposobie rozmowy najbardziej Ci pomaga?' },
  { id: "relacja-14", category: "relacja", depth: "medium", text: 'Co warto częściej celebrować, nawet jeśli jest małe?' },
  { id: "relacja-15", category: "relacja", depth: "medium", text: 'Jakiej wspólnej rzeczy ostatnio nam brakuje?' },
  { id: "relacja-16", category: "relacja", depth: "medium", text: 'Co według Ciebie robimy lepiej niż kilka miesięcy temu?' },
  { id: "relacja-17", category: "relacja", depth: "medium", text: 'Co sprawia, że po trudniejszym dniu nadal czujesz, że jesteśmy razem?' },
  { id: "relacja-18", category: "relacja", depth: "medium", text: 'Jak moglibyśmy lepiej dzielić się planami i oczekiwaniami?' },
  { id: "relacja-19", category: "relacja", depth: "medium", text: 'Co chciałbyś/chciałabyś, żebyśmy częściej robili bez telefonów?' },
  { id: "relacja-20", category: "relacja", depth: "medium", text: 'Która nasza różnica działa na naszą korzyść?' },
  { id: "relacja-21", category: "relacja", depth: "medium", text: 'Jak mogę lepiej pokazywać Ci, że biorę Twoją perspektywę pod uwagę?' },
  { id: "relacja-22", category: "relacja", depth: "medium", text: 'Co daje Ci poczucie, że możesz liczyć na mnie?' },
  { id: "relacja-23", category: "relacja", depth: "medium", text: 'Jaki jeden element naszej codzienności chciałbyś/chciałabyś ulepszyć?' },
  { id: "relacja-24", category: "relacja", depth: "medium", text: 'Co najbardziej pomaga nam wrócić do siebie po napięciu?' },
  { id: "relacja-25", category: "relacja", depth: "medium", text: 'Z czego w naszej relacji jesteś dziś najbardziej zadowolony/a?' },
  { id: "przyszlosc-01", category: "przyszlosc", depth: "medium", text: 'Gdzie chciałbyś/chciałabyś pojechać ze mną choć raz?' },
  { id: "przyszlosc-02", category: "przyszlosc", depth: "medium", text: 'Jak wyglądałby nasz idealny wspólny weekend za kilka lat?' },
  { id: "przyszlosc-03", category: "przyszlosc", depth: "medium", text: 'Jaką tradycję chcielibyśmy kiedyś mieć tylko dla siebie?' },
  { id: "przyszlosc-04", category: "przyszlosc", depth: "medium", text: 'Czego chcielibyśmy razem nauczyć się w przyszłości?' },
  { id: "przyszlosc-05", category: "przyszlosc", depth: "medium", text: 'Jakie miejsce mogłoby kiedyś stać się „naszym miejscem”?' },
  { id: "przyszlosc-06", category: "przyszlosc", depth: "medium", text: 'Jaki wspólny projekt byłoby fajnie kiedyś zrobić?' },
  { id: "przyszlosc-07", category: "przyszlosc", depth: "medium", text: 'Jak wyobrażasz sobie nasze spokojne niedzielne popołudnie za kilka lat?' },
  { id: "przyszlosc-08", category: "przyszlosc", depth: "medium", text: 'Jaką rzecz chcielibyśmy razem zobaczyć na żywo?' },
  { id: "przyszlosc-09", category: "przyszlosc", depth: "medium", text: 'Co warto wpisać na naszą listę „kiedyś zrobimy”?' },
  { id: "przyszlosc-10", category: "przyszlosc", depth: "medium", text: 'Jaką podróż chcielibyśmy zaplanować bez patrzenia na budżet?' },
  { id: "przyszlosc-11", category: "przyszlosc", depth: "medium", text: 'Jaki wspólny nawyk chcielibyśmy mieć za rok?' },
  { id: "przyszlosc-12", category: "przyszlosc", depth: "medium", text: 'Co chcielibyśmy częściej robić, gdy będziemy mieli więcej czasu?' },
  { id: "przyszlosc-13", category: "przyszlosc", depth: "medium", text: 'Jak wyglądałoby miejsce, w którym oboje dobrze byśmy odpoczywali?' },
  { id: "przyszlosc-14", category: "przyszlosc", depth: "medium", text: 'Jaki wspólny cel byłby dla nas ekscytujący, ale nie przytłaczający?' },
  { id: "przyszlosc-15", category: "przyszlosc", depth: "medium", text: 'Jakie małe marzenie możemy spełnić jeszcze w tym roku?' },
  { id: "przyszlosc-16", category: "przyszlosc", depth: "medium", text: 'Jak wyglądałaby nasza wymarzona spontaniczna sobota?' },
  { id: "przyszlosc-17", category: "przyszlosc", depth: "medium", text: 'Jaką rzecz chcielibyśmy kiedyś kolekcjonować jako wspólne wspomnienia?' },
  { id: "przyszlosc-18", category: "przyszlosc", depth: "medium", text: 'Jaki rodzaj wyjazdów chcielibyśmy robić częściej?' },
  { id: "przyszlosc-19", category: "przyszlosc", depth: "medium", text: 'Jak wyobrażasz sobie nasz wspólny domowy rytuał za kilka lat?' },
  { id: "przyszlosc-20", category: "przyszlosc", depth: "medium", text: 'Co chciałbyś/chciałabyś przeżyć ze mną po raz pierwszy?' },
  { id: "przyszlosc-21", category: "przyszlosc", depth: "medium", text: 'Jaką rzecz warto zacząć odkładać na wspólne „kiedyś”?' },
  { id: "przyszlosc-22", category: "przyszlosc", depth: "medium", text: 'Jakie miejsce w Polsce chcielibyśmy razem odkryć?' },
  { id: "przyszlosc-23", category: "przyszlosc", depth: "medium", text: 'Co mogłoby być naszym corocznym zwyczajem?' },
  { id: "przyszlosc-24", category: "przyszlosc", depth: "medium", text: 'Jaką umiejętność chcielibyśmy opanować jako duet?' },
  { id: "przyszlosc-25", category: "przyszlosc", depth: "medium", text: 'Jaki jeden plan na najbliższe miesiące najbardziej Cię cieszy?' },
  { id: "dziecinstwo-01", category: "dziecinstwo", depth: "medium", text: 'Jakie miejsce z dzieciństwa pamiętasz najcieplej?' },
  { id: "dziecinstwo-02", category: "dziecinstwo", depth: "medium", text: 'Co najczęściej robiłeś/aś po szkole jako dziecko?' },
  { id: "dziecinstwo-03", category: "dziecinstwo", depth: "medium", text: 'Jaka bajka albo program był kiedyś dla Ciebie bardzo ważny?' },
  { id: "dziecinstwo-04", category: "dziecinstwo", depth: "medium", text: 'Jakie jedzenie najbardziej kojarzy Ci się z domem?' },
  { id: "dziecinstwo-05", category: "dziecinstwo", depth: "medium", text: 'Jaki był Twój ulubiony sposób spędzania wakacji?' },
  { id: "dziecinstwo-06", category: "dziecinstwo", depth: "medium", text: 'Czego jako dziecko bardzo chciałeś/aś się nauczyć?' },
  { id: "dziecinstwo-07", category: "dziecinstwo", depth: "medium", text: 'Jaki prezent z dzieciństwa pamiętasz do dziś?' },
  { id: "dziecinstwo-08", category: "dziecinstwo", depth: "medium", text: 'Który szkolny przedmiot naprawdę lubiłeś/aś?' },
  { id: "dziecinstwo-09", category: "dziecinstwo", depth: "medium", text: 'Jakie było Twoje pierwsze większe hobby?' },
  { id: "dziecinstwo-10", category: "dziecinstwo", depth: "medium", text: 'Z czego jako dziecko byłeś/byłaś szczególnie dumny/a?' },
  { id: "dziecinstwo-11", category: "dziecinstwo", depth: "medium", text: 'Jakie rodzinne święto albo zwyczaj pamiętasz najlepiej?' },
  { id: "dziecinstwo-12", category: "dziecinstwo", depth: "medium", text: 'Jaki zapach najmocniej przypomina Ci dzieciństwo?' },
  { id: "dziecinstwo-13", category: "dziecinstwo", depth: "medium", text: 'Kim chciałeś/aś zostać, kiedy byłeś/byłaś mały/a?' },
  { id: "dziecinstwo-14", category: "dziecinstwo", depth: "medium", text: 'Jaka zabawka była dla Ciebie kiedyś najważniejsza?' },
  { id: "dziecinstwo-15", category: "dziecinstwo", depth: "medium", text: 'Co robiłeś/aś, kiedy jako dziecko miałeś/aś gorszy humor?' },
  { id: "dziecinstwo-16", category: "dziecinstwo", depth: "medium", text: 'Jak wyglądał Twój idealny dzień wolny jako dziecko?' },
  { id: "dziecinstwo-17", category: "dziecinstwo", depth: "medium", text: 'Jaka historia z podstawówki nadal Cię śmieszy?' },
  { id: "dziecinstwo-18", category: "dziecinstwo", depth: "medium", text: 'Co było pierwszą rzeczą, na którą długo oszczędzałeś/aś?' },
  { id: "dziecinstwo-19", category: "dziecinstwo", depth: "medium", text: 'Jakiej rzeczy bałeś/aś się jako dziecko, a dziś wydaje Ci się zabawna?' },
  { id: "dziecinstwo-20", category: "dziecinstwo", depth: "medium", text: 'Jakie miejsce odwiedzane z rodziną najlepiej pamiętasz?' },
  { id: "dziecinstwo-21", category: "dziecinstwo", depth: "medium", text: 'Jaki był Twój pierwszy koncert, mecz albo większe wydarzenie?' },
  { id: "dziecinstwo-22", category: "dziecinstwo", depth: "medium", text: 'Jakie powiedzenie z domu rodzinnego pamiętasz do dziś?' },
  { id: "dziecinstwo-23", category: "dziecinstwo", depth: "medium", text: 'Co jako dziecko robiłeś/aś kompletnie inaczej niż dziś?' },
  { id: "dziecinstwo-24", category: "dziecinstwo", depth: "medium", text: 'Jaka osoba z dzieciństwa miała na Ciebie dobry wpływ?' },
  { id: "dziecinstwo-25", category: "dziecinstwo", depth: "medium", text: 'Jakie małe dziecięce marzenie nadal brzmi dla Ciebie fajnie?' },
  { id: "codziennosc-01", category: "codziennosc", depth: "light", text: 'Wolisz zaczynać dzień spokojnie czy od razu coś robić?' },
  { id: "codziennosc-02", category: "codziennosc", depth: "light", text: 'Co najbardziej lubisz jeść, gdy kompletnie nie chce Ci się gotować?' },
  { id: "codziennosc-03", category: "codziennosc", depth: "light", text: 'Jaki jest Twój ulubiony sposób na wolny wieczór w domu?' },
  { id: "codziennosc-04", category: "codziennosc", depth: "light", text: 'Co najczęściej robisz jako pierwsze po powrocie do domu?' },
  { id: "codziennosc-05", category: "codziennosc", depth: "light", text: 'Jak lubisz planować weekend: wcześniej czy w ostatniej chwili?' },
  { id: "codziennosc-06", category: "codziennosc", depth: "light", text: 'Wolisz wspólne zakupy czy każde osobno?' },
  { id: "codziennosc-07", category: "codziennosc", depth: "light", text: 'Jaka godzina dnia jest dla Ciebie zwykle najlepsza?' },
  { id: "codziennosc-08", category: "codziennosc", depth: "light", text: 'Co pomaga Ci dobrze zacząć poranek?' },
  { id: "codziennosc-09", category: "codziennosc", depth: "light", text: 'Jak wygląda dla Ciebie naprawdę dobry wieczór po pracy lub zajęciach?' },
  { id: "codziennosc-10", category: "codziennosc", depth: "light", text: 'Wolisz ciszę w domu czy muzykę w tle?' },
  { id: "codziennosc-11", category: "codziennosc", depth: "light", text: 'Jaki domowy obowiązek przeszkadza Ci najmniej?' },
  { id: "codziennosc-12", category: "codziennosc", depth: "light", text: 'Jaki domowy obowiązek najchętniej oddałbyś/oddałabyś komuś innemu?' },
  { id: "codziennosc-13", category: "codziennosc", depth: "light", text: 'Wolisz mieć jeden duży plan na dzień czy kilka małych?' },
  { id: "codziennosc-14", category: "codziennosc", depth: "light", text: 'Co najczęściej wybierasz, gdy chcesz zrobić sobie małą przyjemność?' },
  { id: "codziennosc-15", category: "codziennosc", depth: "light", text: 'Jak lubisz spędzać deszczowy dzień?' },
  { id: "codziennosc-16", category: "codziennosc", depth: "light", text: 'Co jest Twoim ulubionym szybkim śniadaniem?' },
  { id: "codziennosc-17", category: "codziennosc", depth: "light", text: 'Wolisz wcześniej wiedzieć o planach czy lubisz niespodzianki?' },
  { id: "codziennosc-18", category: "codziennosc", depth: "light", text: 'Jak długo potrzebujesz rano, żeby naprawdę się rozbudzić?' },
  { id: "codziennosc-19", category: "codziennosc", depth: "light", text: 'Jaki rodzaj wiadomości ode mnie najbardziej lubisz dostać w ciągu dnia?' },
  { id: "codziennosc-20", category: "codziennosc", depth: "light", text: 'Co najczęściej robisz podczas krótkiej przerwy?' },
  { id: "codziennosc-21", category: "codziennosc", depth: "light", text: 'Wolisz wyjść gdzieś bez planu czy mieć konkretny cel?' },
  { id: "codziennosc-22", category: "codziennosc", depth: "light", text: 'Jaka mała rzecz w domu najbardziej poprawia Ci komfort?' },
  { id: "codziennosc-23", category: "codziennosc", depth: "light", text: 'Co sprawia, że wieczorem łatwiej Ci odłożyć telefon?' },
  { id: "codziennosc-24", category: "codziennosc", depth: "light", text: 'Jaki wspólny posiłek najbardziej lubisz?' },
  { id: "codziennosc-25", category: "codziennosc", depth: "light", text: 'Jak wygląda dla Ciebie idealne 30 minut tylko dla siebie?' },
  { id: "marzenia-01", category: "marzenia", depth: "medium", text: 'Gdyby pieniądze i czas nie miały znaczenia, czego chciałbyś/chciałabyś spróbować?' },
  { id: "marzenia-02", category: "marzenia", depth: "medium", text: 'Jakie miejsce na świecie najbardziej Cię ciekawi?' },
  { id: "marzenia-03", category: "marzenia", depth: "medium", text: 'Jaka rzecz od dawna chodzi Ci po głowie, ale ciągle jej nie zaczynasz?' },
  { id: "marzenia-04", category: "marzenia", depth: "medium", text: 'Jakiego doświadczenia chciałbyś/chciałabyś choć raz spróbować?' },
  { id: "marzenia-05", category: "marzenia", depth: "medium", text: 'Co chciałbyś/chciałabyś umieć robić naprawdę dobrze?' },
  { id: "marzenia-06", category: "marzenia", depth: "medium", text: 'Jak wyglądałby Twój wymarzony miesiąc bez obowiązków?' },
  { id: "marzenia-07", category: "marzenia", depth: "medium", text: 'Jakie małe marzenie da się spełnić szybciej, niż nam się wydaje?' },
  { id: "marzenia-08", category: "marzenia", depth: "medium", text: 'Jaki projekt zrobiłbyś/zrobiłabyś dla czystej satysfakcji?' },
  { id: "marzenia-09", category: "marzenia", depth: "medium", text: 'Jakiego miejsca chciałbyś/chciałabyś kiedyś nazwać domem choć na chwilę?' },
  { id: "marzenia-10", category: "marzenia", depth: "medium", text: 'Co chciałbyś/chciałabyś zrobić, zanim skończy się ten rok?' },
  { id: "marzenia-11", category: "marzenia", depth: "medium", text: 'Jakie wspomnienie chciałbyś/chciałabyś stworzyć razem ze mną?' },
  { id: "marzenia-12", category: "marzenia", depth: "medium", text: 'Co byłoby dla Ciebie spełnieniem małego, prywatnego marzenia?' },
  { id: "marzenia-13", category: "marzenia", depth: "medium", text: 'Jaki koncert, wydarzenie albo miejsce chciałbyś/chciałabyś zobaczyć na żywo?' },
  { id: "marzenia-14", category: "marzenia", depth: "medium", text: 'Jakie hobby kusi Cię od dawna?' },
  { id: "marzenia-15", category: "marzenia", depth: "medium", text: 'Jaką rzecz chciałbyś/chciałabyś kiedyś zrobić spontanicznie?' },
  { id: "marzenia-16", category: "marzenia", depth: "medium", text: 'Gdybyśmy mieli miesiąc wolnego, jak byśmy go wykorzystali?' },
  { id: "marzenia-17", category: "marzenia", depth: "medium", text: 'Co chciałbyś/chciałabyś kiedyś stworzyć własnymi rękami?' },
  { id: "marzenia-18", category: "marzenia", depth: "medium", text: 'Jaki typ podróży brzmi dla Ciebie najbardziej ekscytująco?' },
  { id: "marzenia-19", category: "marzenia", depth: "medium", text: 'Jaką jedną rzecz chciałbyś/chciałabyś kiedyś zrobić tylko dlatego, że brzmi zabawnie?' },
  { id: "marzenia-20", category: "marzenia", depth: "medium", text: 'Co chciałbyś/chciałabyś mieć więcej w swoim życiu za kilka lat?' },
  { id: "marzenia-21", category: "marzenia", depth: "medium", text: 'Jak wyglądałby Twój wymarzony dzień, gdyby nie było żadnych ograniczeń?' },
  { id: "marzenia-22", category: "marzenia", depth: "medium", text: 'Jakie marzenie z dawnych lat nadal gdzieś w Tobie siedzi?' },
  { id: "marzenia-23", category: "marzenia", depth: "medium", text: 'Co chcielibyśmy kiedyś zrobić razem i nikomu wcześniej o tym nie mówiliśmy?' },
  { id: "marzenia-24", category: "marzenia", depth: "medium", text: 'Jaką rzecz chciałbyś/chciałabyś kiedyś odważyć się zrobić?' },
  { id: "marzenia-25", category: "marzenia", depth: "medium", text: 'Co jest dziś Twoim najbardziej realnym marzeniem?' },
  { id: "hipotetyczne-01", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy jutro dostali darmowe bilety lotnicze w dowolne miejsce, gdzie lecimy?' },
  { id: "hipotetyczne-02", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mogli na tydzień zamienić się życiem z dowolną fikcyjną parą, kogo wybierasz?' },
  { id: "hipotetyczne-03", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy musieli przez miesiąc mieszkać bez internetu, co robilibyśmy wieczorami?' },
  { id: "hipotetyczne-04", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mogli zatrzymać jeden dzień z naszego życia i przeżyć go jeszcze raz, który?' },
  { id: "hipotetyczne-05", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy dostali mały domek w dowolnym miejscu, gdzie by stał?' },
  { id: "hipotetyczne-06", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mieli nauczyć się razem jednej kompletnie nowej rzeczy, czego?' },
  { id: "hipotetyczne-07", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mogli przez rok pracować z dowolnego miejsca, gdzie byśmy pojechali?' },
  { id: "hipotetyczne-08", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy musieli urządzić mieszkanie w jednym stylu, jaki wybierasz?' },
  { id: "hipotetyczne-09", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mieli wspólny podcast, o czym by był?' },
  { id: "hipotetyczne-10", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mogli cofnąć się razem do jednego momentu historycznego, który wybierasz?' },
  { id: "hipotetyczne-11", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mieli przez tydzień zamienić się telefonami, co byłoby najdziwniejsze?' },
  { id: "hipotetyczne-12", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mogli mieć dowolne zwierzę bez żadnych problemów, jakie?' },
  { id: "hipotetyczne-13", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mieli jedną dodatkową godzinę każdego dnia tylko dla nas, co z nią robimy?' },
  { id: "hipotetyczne-14", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mogli mieszkać przez miesiąc w dowolnym filmie, który wybierasz?' },
  { id: "hipotetyczne-15", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mieli założyć wspólny kanał, co byśmy na nim robili?' },
  { id: "hipotetyczne-16", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mogli przenieść jedno miejsce z wakacji bliżej domu, które?' },
  { id: "hipotetyczne-17", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mieli przez rok nie kupować jednej kategorii rzeczy, z czego najłatwiej zrezygnować?' },
  { id: "hipotetyczne-18", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy dostali 24 godziny bez żadnych obowiązków, od czego zaczynamy?' },
  { id: "hipotetyczne-19", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mogli natychmiast nauczyć się jednego języka, którego?' },
  { id: "hipotetyczne-20", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy musieli wybrać jedno danie na każdą rocznicę, co by to było?' },
  { id: "hipotetyczne-21", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mieli zorganizować najbardziej absurdalną randkę, co by się na niej działo?' },
  { id: "hipotetyczne-22", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mogli zachować na zawsze jeden wspólny zapach, smak albo dźwięk, co wybierasz?' },
  { id: "hipotetyczne-23", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy na jeden dzień zamienili się charakterami, co byłoby najzabawniejsze?' },
  { id: "hipotetyczne-24", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mogli mieć wspólną tajną bazę, gdzie by się znajdowała?' },
  { id: "hipotetyczne-25", category: "hipotetyczne", depth: "light", text: 'Gdybyśmy mogli dziś powiedzieć „tak” jednemu spontanicznemu pomysłowi, co by to było?' },
  { id: "szczerze-01", category: "szczerze", depth: "deep", text: 'Co jest dla Ciebie najtrudniejsze do powiedzenia, kiedy jesteś zdenerwowany/a?' },
  { id: "szczerze-02", category: "szczerze", depth: "deep", text: 'Po czym poznajesz, że potrzebujesz przestrzeni zamiast rozmowy?' },
  { id: "szczerze-03", category: "szczerze", depth: "deep", text: 'Co najbardziej pomaga Ci wrócić do spokoju po napięciu?' },
  { id: "szczerze-04", category: "szczerze", depth: "deep", text: 'Jak chciałbyś/chciałabyś, żebym reagował/a, kiedy czujesz się niezrozumiany/a?' },
  { id: "szczerze-05", category: "szczerze", depth: "deep", text: 'Co sprawia, że podczas trudnej rozmowy zamykasz się bardziej?' },
  { id: "szczerze-06", category: "szczerze", depth: "deep", text: 'Jakiej formy przeprosin potrzebujesz, żeby naprawdę je poczuć?' },
  { id: "szczerze-07", category: "szczerze", depth: "deep", text: 'Co jest dla Ciebie ważniejsze po konflikcie: czas, rozmowa czy gest?' },
  { id: "szczerze-08", category: "szczerze", depth: "deep", text: 'Kiedy najtrudniej jest Ci poprosić o wsparcie?' },
  { id: "szczerze-09", category: "szczerze", depth: "deep", text: 'Co chciałbyś/chciałabyś, żebym lepiej rozumiał/a o Twoich reakcjach?' },
  { id: "szczerze-10", category: "szczerze", depth: "deep", text: 'Jak rozpoznajesz u siebie moment, w którym emocje zaczynają przejmować rozmowę?' },
  { id: "szczerze-11", category: "szczerze", depth: "deep", text: 'Co pomaga Ci poczuć się bezpiecznie podczas trudnego tematu?' },
  { id: "szczerze-12", category: "szczerze", depth: "deep", text: 'Jak najlepiej dać Ci znać, że nie chcę walczyć, tylko zrozumieć?' },
  { id: "szczerze-13", category: "szczerze", depth: "deep", text: 'Co możesz zrobić sam/a, żeby trudna rozmowa była dla nas spokojniejsza?' },
  { id: "szczerze-14", category: "szczerze", depth: "deep", text: 'Co chciałbyś/chciałabyś częściej mówić wprost zamiast liczyć, że się domyślę?' },
  { id: "szczerze-15", category: "szczerze", depth: "deep", text: 'Jak reagujesz, kiedy boisz się, że zostaniesz odrzucony/a albo zignorowany/a?' },
  { id: "szczerze-16", category: "szczerze", depth: "deep", text: 'Co sprawia, że łatwiej Ci przyznać: „tu mogłem/mogłam zrobić coś lepiej”?' },
  { id: "szczerze-17", category: "szczerze", depth: "deep", text: 'Jakiego zachowania podczas konfliktu najbardziej chciałbyś/chciałabyś unikać?' },
  { id: "szczerze-18", category: "szczerze", depth: "deep", text: 'Co pomaga Ci odróżnić obawę od tego, co naprawdę się wydarzyło?' },
  { id: "szczerze-19", category: "szczerze", depth: "deep", text: 'Jak możemy lepiej kończyć trudne rozmowy, nawet jeśli nie rozwiązaliśmy wszystkiego?' },
  { id: "szczerze-20", category: "szczerze", depth: "deep", text: 'Co chciałbyś/chciałabyś usłyszeć ode mnie, kiedy jest Ci naprawdę ciężko?' },
  { id: "szczerze-21", category: "szczerze", depth: "deep", text: 'Jak możemy sygnalizować sobie, że potrzebujemy przerwy bez poczucia odrzucenia?' },
  { id: "szczerze-22", category: "szczerze", depth: "deep", text: 'Co w trudnych chwilach pomaga Ci pamiętać, że nadal jesteśmy po tej samej stronie?' },
  { id: "szczerze-23", category: "szczerze", depth: "deep", text: 'Jaka Twoja potrzeba bywa najtrudniejsza do zakomunikowania?' },
  { id: "szczerze-24", category: "szczerze", depth: "deep", text: 'Co chciałbyś/chciałabyś, żebyśmy robili inaczej, gdy oboje jesteśmy zmęczeni?' },
  { id: "szczerze-25", category: "szczerze", depth: "deep", text: 'Jaka jedna rzecz mogłaby sprawić, że nasze trudne rozmowy byłyby bezpieczniejsze dla nas obojga?' },
];

export function getQuestionById(id: string): Question | undefined {
  return QUESTIONS.find((question) => question.id === id);
}

export function getCategory(key: QuestionCategoryKey): QuestionCategory {
  return QUESTION_CATEGORIES.find((category) => category.key === key) ?? QUESTION_CATEGORIES[0];
}

export function isQuestionCategoryKey(value: string): value is QuestionCategoryKey {
  return QUESTION_CATEGORIES.some((category) => category.key === value);
}
